hash-format = "sha256"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fda319290cfe268fdc7c6c6ca8dcad24e51c1de98442f23f2a41d657b26fc8d0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b1ff809ec34348860c3a403f3d5210f7386ddcda8f0d19c5ff4533fd22abeb08"
metafile = true

[[files]]
file = "mods/couplings.pw.toml"
hash = "9ec56a224c0b32ae551909bbdabec0f87194682c3e498edda5d53d4a0dac314c"
metafile = true

[[files]]
file = "mods/discord4fabric.pw.toml"
hash = "eef4678890fcb33bc6dbb51767c49ff90d0a2316627d4cfc6b35d89089682e4a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f6bc53688790ec2d88c96568f6d7569bf0111931c569cf64b511cdbe95090c82"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4c1b893d87c51588985c483fe33193ca03cf3673de998eef6eeb850d8928e7ab"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "feaedf6b6d73530c0289d9c7aa4149823343d2a7f9893f7b81e8c7c003763f31"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "c038a6ea641541af0aee754c41df71ccb662245863cecb43d64c202baf561291"
metafile = true

[[files]]
file = "mods/log-cleaner.pw.toml"
hash = "65a25b591b2afa0767de3426a944495a52721d71a7328daa3639e60dd88a04eb"
metafile = true

[[files]]
file = "mods/mcunsafe-0.0.0-build.local.jar"
hash = "a43b4194177d90e141d6214fe05e63879d94aa27ecf3b29252e3b0e6fef66dc8"

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "5b43c0fc6904ad4480c8ed596411c6e24172f8320ccd63de97b4ce2e7e0f90a5"
metafile = true

[[files]]
file = "mods/ottah.pw.toml"
hash = "47d4e6d759f40f3838f4286b891837bbcfe653395576b40f0c473f0c5bed8285"
metafile = true

[[files]]
file = "mods/plymouth-anti-xray.pw.toml"
hash = "4809dda00e0db763f5dd8a58ddafb5d75d70ba4c3a1ec764a95865d208428b44"
metafile = true

[[files]]
file = "mods/polymc.pw.toml"
hash = "60a9f2a1f2ed39df2ca57f6e57246183f080e71d9331572a2c54c4ff41ee6f7d"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "aa31031741702bc20d76d3f843c103c39a1a13aaea49e7003757b6913fc4b01c"
metafile = true

[[files]]
file = "mods/raknetify.pw.toml"
hash = "82f5f6f055d70725d71947c519786eaf7757b8221ad5e2d5c4398ecf0360812a"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "82ced750111c5c106501c824b4883b111c86e6ea96a637ef37726a9ddb5f1cdd"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "e50fbf20fc8c0a816f3325959a1ceab64c160b0b3bcc83f701ffdbfa771dad4b"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
hash = "79bf46f1892bfb23ff9a69b16d0f9147da33809021f0f2ef2f73ae7d10bbefec"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "930afd91b92eb34ec0706647028327674fa7ada4a4395e8b7dca1e4e1c4d839c"
metafile = true
